version: "3"
services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - /data/mongodb
  app:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
